import { PageHeader } from "../../_components/PageHeader";
import { PlaceholderPanel } from "../../_components/PlaceholderPanel";

const analysisInputs = ["Company", "Product", "Target region", "CSV sample file", "Scoring profile"];

export default function RunAnalysisPage() {
  return (
    <div>
      <PageHeader
        eyebrow="Opportunity scoring"
        title="Run analysis"
        description="Prepare an analysis job that will combine product data, public sources, CSV fallback data, and backend AI-generated insights."
      />
      <div className="grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">
        <PlaceholderPanel title="Analysis setup">
          <form className="grid gap-4" aria-label="Analysis run placeholder form">
            {analysisInputs.map((input) => (
              <label key={input} className="grid gap-2">
                <span className="text-sm font-medium text-slate-700">{input}</span>
                <input
                  className="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm outline-none transition focus:border-river focus:ring-2 focus:ring-river/20"
                  placeholder={`Select ${input.toLowerCase()}`}
                  type="text"
                />
              </label>
            ))}
            <button
              className="mt-2 rounded-md bg-river px-4 py-2.5 text-sm font-semibold text-white"
              type="button"
            >
              Queue analysis
            </button>
          </form>
        </PlaceholderPanel>
        <PlaceholderPanel title="Expected output">
          <ul className="grid gap-3">
            <li>Market opportunity score with factor-level explanations.</li>
            <li>Source summaries for marketplace, trade, search, video, and social signals.</li>
            <li>AI-assisted listing copy drafts generated by backend services.</li>
            <li>Report-ready recommendations for overseas expansion decisions.</li>
          </ul>
        </PlaceholderPanel>
      </div>
    </div>
  );
}
